module.exports.AUTHED_USER_CONSTANTS = {
        SET_AUTHED_USER : "SET_AUTHED_USER",
        REMOVE_AUTHED_USER: "REMOVE_AUTHED_USER"
}

module.exports.USERS_CONSTANTS = {
        RECEIVE_ALL_USERS : "RECEIVE_ALL_USERS"
}

module.exports.QUESTIONS_CONSTANTS = {
        RECEIVE_ALL_QUESTIONS : "RECEIVE_ALL_QUESTIONS",
        ADD_QUESTION: "ADD_QUESTION",
        AUTHED_USER_ADD_QUESTION: "AUTHED_USER_ADD_QUESTION",
        ANSWER_QUESTION: "ANSWER_QUESTION",
        AUTHED_USER_ANSWER_QUESTION: "AUTHED_USER_ANSWER_QUESTION",

}
